<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ProductionActivity;
use App\Models\MarketingOrder; // Tambahkan ini
use App\Models\User;
use Carbon\Carbon;

class ProductionTrendSeeder extends Seeder
{
    public function run()
    {
        $user = User::where('role', 'operator')->first() ?? User::first();
        // Ambil satu order sebagai sampel agar relasi database tidak pecah
        $order = MarketingOrder::first();

        if (!$user || !$order) {
            $this->command->error("Pastikan ada data User dan MarketingOrder di database!");
            return;
        }

        for ($i = 0; $i <= 7; $i++) {
            $date = Carbon::now()->subDays($i);
            $jumlahInput = rand(5, 15); 

            for ($j = 0; $j < $jumlahInput; $j++) {
                ProductionActivity::create([
                    'operator_id' => $user->id,
                    // Kita ganti 'sap_no' dengan 'marketing_order_id' (Foreign Key)
                    'marketing_order_id' => $order->id, 
                    'division_name' => collect(['Knitting (Rajutan)', 'SCR / Dyeing (Pewarnaan)', 'Stenter', 'Pengujian'])->random(),
                    'status' => 'completed',
                    // Data teknis opsional jika kolom ini REQUIRED di database Anda
                    'technical_data' => ['note' => 'Generated by System'], 
                    'created_at' => $date->copy()->addHours(rand(1, 23)),
                    'updated_at' => $date,
                ]);
            }
        }

        $this->command->info("Seeder diperbaiki! Data tren berhasil disuntikkan.");
    }
}