import React, { useState, useRef } from 'react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, usePage } from '@inertiajs/react';
import axios from 'axios';
import ReactToPrint from 'react-to-print';

// --- IMPORT KOMPONEN MODULAR EKOSISTEM ---
import KnittingForm from './Forms/KnittingForm';
import DyeingForm from './Forms/DyeingForm';
import RelaxDryerForm from './Forms/RelaxDryerForm';
import CompactorForm from './Forms/CompactorForm';
import HeatSettingForm from './Forms/HeatSettingForm';
import StenterForm from './Forms/StenterForm';
import TumblerForm from './Forms/TumblerForm';
import FleeceForm from './Forms/FleeceForm';
import PengujianForm from './Forms/PengujianForm';
import QEForm from './Forms/QEForm';

// --- KOMPONEN DESAIN LABEL (80mm) ---
const LabelCetak = React.forwardRef(({ order, qrCode }, ref) => (
    <div ref={ref} className="p-4 w-[80mm] bg-white text-black font-mono border-2 border-black">
        <div className="text-center font-black border-b-2 border-black mb-2 text-sm uppercase italic">
            DUNIATEX PRODUCTION LABEL
        </div>
        <div className="flex justify-between items-start gap-2">
            <div className="text-[10px] space-y-1 uppercase font-bold flex-1">
                <div>SAP: <span className="text-sm font-black">{order.sap_no}</span></div>
                <div>ART: {order.art_no}</div>
                <div>PLG: {order.pelanggan}</div>
                <div className="pt-2">WARNA: {order.warna}</div>
            </div>
            <div 
                dangerouslySetInnerHTML={{ __html: qrCode }} 
                className="w-20 h-20 border border-gray-100 p-1"
            />
        </div>
        <div className="mt-2 text-[7px] text-center border-t border-black pt-1 italic font-sans">
            Generated by Duniatex System • {new Date().toLocaleString()}
        </div>
    </div>
));

export default function LogBook({ auth, division }) {
    const [sapNo, setSapNo] = useState('');
    const [orderData, setOrderData] = useState(null);
    const [loading, setLoading] = useState(false);
    const [submitting, setSubmitting] = useState(false);
    const [showConfirmModal, setShowConfirmModal] = useState(false);
    const [formData, setFormData] = useState({});
    const [errorMessage, setErrorMessage] = useState('');
    
    const [labelData, setLabelData] = useState(null);
    const componentRef = useRef();

    const { workOrders = [] } = usePage().props;

    const formatDivisionName = (div) => {
        const map = { 
            'knitting': 'Knitting (Rajutan)', 
            'scr-dyeing': 'SCR / Dyeing (Pewarnaan)',
            'relax-dryer': 'Relax Dryer',
            'compactor': 'Compactor',
            'heat-setting': 'Heat Setting',
            'stenter': 'Stenter',
            'tumbler': 'Tumbler',
            'fleece': 'Fleece',
            'pengujian': 'Pengujian',
            'qe': 'QE'
        };
        return map[div] || div;
    };

    const handleSelectOrder = (order) => {
        setOrderData(order);
        setSapNo(order.sap_no.toString());
        setFormData({});
        setErrorMessage('');
    };

    const searchSap = async () => {
        if (!sapNo) return;
        setLoading(true);
        setErrorMessage('');
        try {
            const response = await axios.get(`/api/order-details/${sapNo}`);
            if (response.data) {
                setOrderData(response.data);
                setFormData({});
            } else {
                setErrorMessage(`SAP ${sapNo} tidak ditemukan.`);
            }
        } catch (err) { 
            setErrorMessage(`SAP ${sapNo} tidak ditemukan.`); 
        } finally { 
            setLoading(false); 
        }
    };

    const handleInputChange = (field, value) => {
        setFormData(prev => ({ ...prev, [field]: value }));
    };

    const handleSubmitClick = (e) => {
        if (e) e.preventDefault();
        setShowConfirmModal(true);
    };

    const confirmSubmit = async () => {
        setShowConfirmModal(false);
        setSubmitting(true);
        try {
            const payload = {
                sap_no: parseInt(sapNo),
                division_name: division,
                technical_data: formData,
            };
            await axios.post('/production/logs', payload);
            const labelRes = await axios.get(`/api/label/${sapNo}`);
            setLabelData(labelRes.data);
            setSubmitting(false);
        } catch (err) { 
            setErrorMessage('Gagal menyimpan laporan.'); 
            setSubmitting(false); 
        }
    };

    const renderFormByDivision = () => {
        const props = { formData, onInputChange: handleInputChange, onSubmit: handleSubmitClick };
        const divLower = division.toLowerCase();

        switch (divLower) {
            case 'knitting': return <KnittingForm {...props} />;
            case 'scr-dyeing': return <DyeingForm {...props} />;
            case 'relax-dryer': return <RelaxDryerForm {...props} />;
            case 'compactor': return <CompactorForm {...props} />;
            case 'heat-setting': return <HeatSettingForm {...props} />;
            case 'stenter': return <StenterForm {...props} />;
            case 'tumbler': return <TumblerForm {...props} />;
            case 'fleece': return <FleeceForm {...props} />;
            case 'pengujian': return <PengujianForm {...props} />;
            case 'qe': return <QEForm {...props} />;
            default:
                return <div className="p-10 text-center uppercase">Divisi tidak dikenal</div>;
        }
    };

    return (
        <AuthenticatedLayout user={auth.user}>
            <Head title={`LogBook - ${formatDivisionName(division)}`} />
            <div className="py-12 bg-gray-50 min-h-screen">
                <div className="max-w-5xl mx-auto px-4">
                    
                    <div className="bg-[#ED1C24] px-6 py-5 text-white rounded-t-3xl shadow-lg flex justify-between items-center">
                        <h1 className="text-2xl font-black uppercase tracking-tighter italic">📋 LOGBOOK {formatDivisionName(division)}</h1>
                    </div>

                    <div className="bg-white rounded-b-3xl shadow-2xl p-8 border border-gray-100">
                        
                        {/* FITUR PENCARIAN DI ATAS */}
                        {!orderData && (
                            <div className="mb-10 max-w-2xl mx-auto animate-in fade-in slide-in-from-top duration-500">
                                <h2 className="text-xs font-black text-gray-400 uppercase tracking-[0.3em] mb-4 text-center">Cari SAP Manual</h2>
                                <div className="flex gap-2">
                                    <input 
                                        type="number" 
                                        placeholder="Masukkan Nomor SAP..." 
                                        className="flex-1 px-4 py-4 border-2 border-gray-100 rounded-2xl focus:ring-[#ED1C24] focus:border-[#ED1C24] font-black text-lg transition-all" 
                                        value={sapNo} 
                                        onChange={(e) => setSapNo(e.target.value)} 
                                        onKeyPress={(e) => e.key === 'Enter' && searchSap()} 
                                    />
                                    <button 
                                        onClick={searchSap} 
                                        disabled={loading}
                                        className="px-10 py-4 bg-gray-900 text-white font-black rounded-2xl hover:bg-black transition-all text-xs uppercase tracking-widest shadow-lg active:scale-95 disabled:opacity-50"
                                    >
                                        {loading ? '...' : 'CARI'}
                                    </button>
                                </div>
                                {errorMessage && <p className="text-red-500 text-[10px] mt-3 font-bold uppercase text-center">{errorMessage}</p>}
                                
                                <div className="relative my-10 text-center">
                                    <span className="bg-white px-6 text-[10px] font-black text-gray-300 uppercase tracking-[0.5em]">Atau Pilih Dari Antrean</span>
                                    <div className="absolute inset-0 top-1/2 -z-10 border-t border-gray-100"></div>
                                </div>
                            </div>
                        )}

                        {/* SEKSI ANTREAN DI BAWAH PENCARIAN */}
                        {!orderData && (
                            <div className="mb-10">
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                    {workOrders.length > 0 ? workOrders.map(order => (
                                        <div key={order.id} onClick={() => handleSelectOrder(order)} className="bg-white p-6 rounded-2xl border-2 border-gray-50 hover:border-[#ED1C24] cursor-pointer shadow-sm hover:shadow-xl transition-all group relative overflow-hidden">
                                            <div className="flex justify-between items-start mb-4">
                                                <span className="bg-red-50 text-red-600 px-3 py-1 rounded-lg text-[10px] font-black uppercase italic tracking-widest border border-red-100">SAP {order.sap_no}</span>
                                                <span className="text-gray-300 text-[10px] font-black group-hover:text-red-600 uppercase tracking-widest">Mulai Kerja →</span>
                                            </div>
                                            <h4 className="text-xl font-black text-gray-900 leading-tight uppercase tracking-tighter">{order.pelanggan}</h4>
                                            <p className="text-[10px] text-gray-500 font-bold uppercase tracking-widest border-t pt-3 mt-3">{order.art_no} • {order.warna}</p>
                                            {order.status === 'rework' && (
                                                <div className="mt-3 bg-red-600 p-3 rounded-xl text-[9px] text-white font-black italic animate-pulse shadow-lg shadow-red-200">
                                                    ⚠️ INSTRUKSI REWORK: {order.note_qe}
                                                </div>
                                            )}
                                        </div>
                                    )) : (
                                        <div className="col-span-2 py-10 text-center text-gray-300 font-black uppercase text-[10px] tracking-widest italic border-2 border-dashed border-gray-100 rounded-3xl">Belum ada antrean pekerjaan</div>
                                    )}
                                </div>
                            </div>
                        )}

                        {/* TAMPILAN FORM (Tetap) */}
                        {orderData && (
                            <div className="animate-in fade-in slide-in-from-bottom duration-500">
                                <button onClick={() => {setOrderData(null); setSapNo(''); setErrorMessage('');}} className="mb-6 text-[10px] font-black text-gray-400 hover:text-red-600 flex items-center gap-2 uppercase transition-all tracking-widest">← Kembali ke Antrean</button>
                                
                                <div className="mb-10 bg-gray-900 p-8 rounded-3xl text-white relative overflow-hidden shadow-2xl border-l-8 border-red-600 italic">
                                    <div className="grid grid-cols-2 md:grid-cols-4 gap-8 relative z-10">
                                        <div><p className="text-[8px] text-gray-500 uppercase font-black mb-1">Customer</p><p className="font-black text-sm uppercase">{orderData.pelanggan}</p></div>
                                        <div><p className="text-[8px] text-gray-500 uppercase font-black mb-1">Target Lebar</p><p className="font-black text-lg text-red-500">{orderData.target_lebar} CM</p></div>
                                        <div><p className="text-[8px] text-gray-500 uppercase font-black mb-1">Target GSM</p><p className="font-black text-lg text-red-500">{orderData.target_gramasi} GSM</p></div>
                                        <div><p className="text-[8px] text-gray-500 uppercase font-black mb-1">Warna</p><p className="font-black text-sm uppercase">{orderData.warna}</p></div>
                                    </div>
                                    <div className="absolute top-0 right-0 p-4 opacity-10 font-black text-6xl italic select-none">DUNIATEX</div>
                                </div>

                                {renderFormByDivision()}
                            </div>
                        )}
                    </div>
                </div>
            </div>

            {/* MODAL PRINT LABEL (Tetap) */}
            {labelData && (
                <div className="fixed inset-0 bg-black/90 backdrop-blur-md flex items-center justify-center z-[9999] p-4">
                    <div className="bg-white p-8 rounded-[2.5rem] shadow-2xl flex flex-col items-center gap-6 animate-in zoom-in duration-300">
                        <h3 className="text-xl font-black uppercase text-gray-800 tracking-tighter italic">Cetak Label Roll Selesai</h3>
                        <div className="border-4 border-black shadow-2xl">
                            <LabelCetak ref={componentRef} order={labelData.order} qrCode={labelData.qrcode} />
                        </div>
                        <div className="flex gap-4 w-full">
                            <button onClick={() => window.location.href = '/operator/divisions'} className="flex-1 py-4 bg-gray-100 rounded-2xl font-black uppercase text-xs">Selesai</button>
                            <ReactToPrint
                                trigger={() => <button className="flex-1 py-4 bg-red-600 text-white font-black rounded-2xl shadow-xl hover:bg-red-700 transition-all uppercase text-xs">🖨️ Print Label</button>}
                                content={() => componentRef.current}
                                onAfterPrint={() => window.location.href = '/operator/divisions'}
                            />
                        </div>
                    </div>
                </div>
            )}

            {/* MODAL KONFIRMASI (Tetap) */}
            {showConfirmModal && (
                <div className="fixed inset-0 bg-gray-900/95 backdrop-blur-md flex items-center justify-center z-[9999] p-4 font-sans">
                    <div className="bg-white rounded-[2.5rem] p-10 max-w-sm w-full text-center shadow-2xl border-t-8 border-red-600 transform transition-all animate-in zoom-in duration-300">
                        <h3 className="text-2xl font-black uppercase italic tracking-tighter mb-10">Kirim Laporan?</h3>
                        <div className="flex gap-3">
                            <button onClick={() => setShowConfirmModal(false)} className="flex-1 py-4 bg-gray-100 rounded-2xl font-black uppercase text-[10px]">Batal</button>
                            <button onClick={confirmSubmit} className="flex-1 py-4 bg-[#ED1C24] text-white rounded-2xl font-black uppercase text-[10px] shadow-lg">Ya, Kirim</button>
                        </div>
                    </div>
                </div>
            )}
        </AuthenticatedLayout>
    );
}